name: build

on:
  push:
  pull_request:

jobs:
  build_job:
    runs-on: [self-hosted, docker]
    container:
      image: node:18

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run build
        run: |
          echo "Running on local Docker runner"
          node --version