name: build

on:
  push:
  pull_request:

jobs:
  build_job:
    runs-on: [self-hosted, docker]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run on node:18
        shell: bash
        env:
          MSYS_NO_PATHCONV: 1
        run: |
          WORKSPACE_PATH=$(echo "${{ github.workspace }}" | sed 's/\\/\//g')
          docker run --rm -v "${WORKSPACE_PATH}:/workspace" -w /workspace node:18 sh -c "
            echo 'Running on local Docker runner'
            node --version
          "